// ddd(json_encode([
// "",
// "Pensi",
// "Olahraga",
// "Game Competition",
// "Knowledge Seminar",
// "Visit Artis Favorit",
// "Pulsa",
// "Kuota Internet",
// "Peralatan Sekolah",
// "Uang Saku",
// "Hape",
// "",
// "",
// "",
// "Telkomsel",
// "Indosat",
// "Tri",
// "XL",
// "Axis",
// "Smartfren",
// "ByU",
// "Telkomsel",
// "Indosat",
// "Tri",
// "XL",
// "Axis",
// "Smartfren",
// "ByU",
// "",
// "Nelpon Jernih",
// "Internetan Cepat",
// "Harga Paket Internetan Murah",
// "Kuota Besar",
// "Masa Aktif Panjang",
// "Dibawah 10 ribu",
// "10 ribu - 20 ribu",
// "20 ribu - 30 ribu",
// "30 ribu - 50 ribu",
// "Diatas 50 ribu",
// "Dibawah 2 GB",
// "2 GB - 5 GB",
// "5 GB - 10 GB",
// "10 GB - 15 GB",
// "Diatas 15 GB",
// "Instagram",
// "Facebook",
// "Twitter",
// "Linkedin",
// "Youtube",
// "TikTok",
// "Whatsapp",
// "Line",
// "Streaming Musik",
// "Streaming Video",
// "Streaming Film",
// "Streaming Youtube",
// "Semuanya",
// "Netflix",
// "Disney Hotstar",
// "Maxstream",
// "Vidio",
// "Lainnya",
// "Free Fire",
// "Mobile Legend",
// "PUBG Mobile",
// "Tidak Suka Main Game",
// "Lainnya",
// "Kantin / Koperasi sekolah",
// "Outlet Sekitar Sekolah",
// "Outlet Sekitar Rumah",
// "Indomaret / Alfamart dan sejenisnya",
// "MyTelkomsel / MyXL / MyCare / MySmartfren dan sejenisnya",
// "Bank / E-Wallet / Tokopedia dan sejenisnya",
// ]));